In [ ]:
ARRAY

In [13]:
import numpy as np
x=[1,2,3,4]

y=np.array([1,2,3,4])
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [11]:
l = [] 
for i in range(1,5):
    int_1 = int(input("enter = "))
    l.append(int_1)
print(np.array(l))

enter =  12
enter =  13
enter =  45
enter =  556


[ 12  13  45 556]


In [21]:
ar2 = np.array([[1,2,3,4],[1,6,7,8]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 6 7 8]]
2


In [23]:
ar3 = np.array([[1,2,3,4],[4,5,6,7],[6,8,9,4]])
print(ar3)
print(ar3.ndim)

[[1 2 3 4]
 [4 5 6 7]
 [6 8 9 4]]
2


In [37]:
#zeros array

In [47]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)



[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [49]:
#ones array

In [59]:
ar_one = np.ones(4)
ar_one1 = np.ones((3,4))
print(ar_one)
print(ar_one1)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [65]:
#empty array
ar_em = np.empty(4)
ar_em1 = np.empty((3,4))
print(ar_em)
print(ar_em1)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [73]:
#range
import numpy as np
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [75]:
#Diagonal

In [83]:
ar_dia = np.eye(4)
ar_dia1 = np.eye(3,5)
print(ar_dia)
print()
print(ar_dia1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [87]:
#linspace

In [85]:
ar_lin = np.linspace(1,10,num=5)
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]


In [89]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


In [93]:
#Random Variable

In [95]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.41121824 0.72660469 0.80231243 0.5327418 ]


In [97]:
var1 = np.random.rand(3,4)
print(var1)

[[0.11413447 0.0623402  0.49804431 0.86523505]
 [0.75462775 0.96499122 0.96333986 0.48124596]
 [0.23181546 0.64598181 0.09230556 0.12175986]]


In [99]:
var2 = np.random.randn(4)
print(var2)

[-0.20979294 -0.49066791 -0.80654241  0.07358662]


In [101]:
var3 = np.random.ranf(4)
print(var3)

[0.47519378 0.29728027 0.05464395 0.24634723]


In [103]:
var4 = np.random.randint(4,20,5)
print(var4)

[19 11  5 13 12]


#DATATYPE

In [106]:
import numpy as np
var=np.array([12,34,1,2,34,455,54,32,11,23,45,56])
print("Data Type: ",var.dtype)

Data Type:  int32


In [108]:
var1 = np.array([1.0,1.2,4.5,6.0,7.8,6.9])
print("Data Type: ", var1.dtype)

Data Type:  float64


In [114]:
x = np.array([1,2,3,4],dtype =  np.int8)
print("Data Type: ",x.dtype)

Data Type:  int8


In [116]:
x2 = np.array([1,2,3,4])
new = np.float32(x2)
new_one = np.int_(new)
print("Data Type: ",x2.dtype)
print("Data Type: ",new.dtype)
print("Data Type: ",new_one.dtype)

print(x2)
print(new)
print(new_one)

Data Type:  int32
Data Type:  float32
Data Type:  int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


#Arithmetic Operations

In [119]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var+3
print(varadd)

[4 5 6 7]


In [121]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
varadd = var1+var2
print(varadd)

[ 6  8 10 12]


In [123]:
var = np.array([1,2,3,4])
varsub = var-3
print(varsub)

[-2 -1  0  1]


In [125]:
var3 = np.array([6,7,8,9])
var4 = np.array([22,3,4,5])
varsub =var4-var3
print(varsub)

[16 -4 -4 -4]


In [127]:
var = np.array([1,2,3,4])
varadd = var*3
print(varadd)

[ 3  6  9 12]


In [129]:
var = np.array([1,2,3,4])
varadd = np.reciprocal(var)
print(varadd)

[1 0 0 0]


#Arithmetic functions

In [20]:
import numpy as np

var = np.array([1,4,7,8,3,4,9,0])
print("min :",np.min(var),np.argmin(var))
print("max :",np.max(var),np.argmax(var))
print("sqrt :",np.sqrt(var))

min : 0 7
max : 9 6
sqrt : [1.         2.         2.64575131 2.82842712 1.73205081 2.
 3.         0.        ]


In [18]:
var1 = np.array([[2,1,3],[9,5,6]])
print(np.min(var1,axis=0))

[2 1 3]


In [26]:
var2 = np.array([1,2,3])
print(np.sin(var2))
print(np.cos(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [28]:
import numpy as np

angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


#shape

In [31]:
import numpy as np 
var = np.array([[1,2],[1,2]])
print(var)
print()
print(var.shape)

[[1 2]
 [1 2]]

(2, 2)


In [33]:
var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [49]:
var1 = np.array([1,2,3,4], ndmin=4)
print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


#reshape

In [64]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)
print()

x = var2.reshape(3,2)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [70]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()

x = var3.reshape(2,3,2)
print(x)
print(x.ndim)
print()

one = x.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


#BROADCASTING

In [75]:
var1 = np.array([1,2,3])
print(var1.shape)

var2 = np.array([[1],[2],[3]])
print(var2)


print(var1 + var2)

(3,)
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [83]:
x = np.array([[1],[2]])
print(x.shape)


y = np.array([[1,2,3],[1,2,3]])
print(y.shape)

print(x+y)


(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]


#Indexing

In [5]:
import numpy as np
var = np.array([9,8,7,6])

print(var[1])
print(var[-3])

8
8


In [7]:
var1 = np.array([[9,8,7],[4,5,6]])
print(var1)
print(var1.ndim)
print()
print(var1[0,1])

[[9 8 7]
 [4 5 6]]
2

8


In [9]:
var2 = np.array([[[1,2],[6,7]]])

print(var2)
print(var2.ndim)
print()
print(var2[0,1,1])

[[[1 2]
  [6 7]]]
3

7


#Slicing


In [16]:
import numpy as np

var = np.array([9,8,7,6,5,4,3])
#               0,1,2,3,4,5,6

print(var)
print()
print("2 to End :",var[1: ])
print("Start to 5: ",var[ :5])
print("stop :",var[::2])
      

[9 8 7 6 5 4 3]

2 to End : [8 7 6 5 4 3]
Start to 5:  [9 8 7 6 5]
stop : [9 7 5 3]


In [22]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var1)
print()
print("8 to 5: ",var1[1,1: ])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 to 5:  [8 7 6 5]


#Iterating Numpy Arrays

In [27]:
x = [9,8,7,6,5,4,3,2,1,0]
for i in x:
    print(i)

9
8
7
6
5
4
3
2
1
0


In [29]:
var1 = np.array([9,8,7,6,5,4])

print(var1)
print()
for i in var1:
    print(i)


[9 8 7 6 5 4]

9
8
7
6
5
4


In [35]:
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var2)
print()

for j in var2:
    print(j)

print()

for k in var2:
    for l in k:
        print(l)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [39]:
var3 = np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i in var3:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [1 2 3 4]]]
3

1
2
3
4
1
2
3
4


In [43]:
var3 = np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i in np.nditer(var3):
    print(i)

[[[1 2 3 4]
  [1 2 3 4]]]
3

1
2
3
4
1
2
3
4


In [53]:
import numpy as np

var3 = np.array([[[1, 2, 3, 4], [1, 2, 3, 4]]])
print(var3)
print(var3.ndim)
print()

for i in np.nditer(var3, flags=['buffered'], op_dtypes=['S']):
    print(i)


[[[1 2 3 4]
  [1 2 3 4]]]
3

b'1'
b'2'
b'3'
b'4'
b'1'
b'2'
b'3'
b'4'


In [55]:
import numpy as np

var3 = np.array([[[1, 2, 3, 4], [1, 2, 3, 4]]])
print(var3)
print(var3.ndim)
print()

for i,d in np.ndenumerate(var3):
    print(i,d)


[[[1 2 3 4]
  [1 2 3 4]]]
3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


#COPY VS VIEW

In [67]:
import numpy as np

var = np.array([1,2,3,4])
co = var.copy()
var[1]=40
print("var: ", var)
print("copy: ",co)

var:  [ 1 40  3  4]
copy:  [1 2 3 4]


In [71]:
var1 = np.array([99,8,7,6,5])
vi = var1.view()
var1[1]=40
print("var1: ",var1)
print("view: ",vi)

var1:  [99 40  7  6  5]
view:  [99 40  7  6  5]


In [3]:
import numpy as np

var1 = np.array([1,2,3,4])
var2 = np.array([9,8,7,6])
ar = np.concatenate((var1,var2))
print(ar)

[1 2 3 4 9 8 7 6]


In [9]:
var = np.array([[1,2],[3,4]])
var1 = np.array([[9,8],[7,6]])

ar_new = np.concatenate((var,var1),axis=1)
ar_new1 = np.concatenate((var,var1),axis=0)
print(var)
print()
print(var1)
print()
print(ar_new)
print(ar_new1)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]
[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [17]:
var_1 =np.array([1,2,3,4])
var_2 =np.array([9,8,7,6])
arr = np.stack((var_1,var_2),axis=1)
arr1 = np.hstack((var_1,var_2))   #row
arr2 = np.vstack((var_1,var_2))   #column
arr3 = np.dstack((var_1,var_2))   #height

print(arr)
print()
print(arr1)
print()
print(arr2)
print()
print(arr3)


[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


In [19]:
import numpy as np

var = np.array([1,2,3,4,5,6])

print(var)

ar = np.array_split(var,3)

print()
print(ar)

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]


In [41]:
var1 = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(var)
print(var.ndim)
ar1= np.array_split(var,3)
print()
print(ar1)
print(var[0])

[1 2 3 4 5 6]
1

[array([1, 2]), array([3, 4]), array([5, 6])]
1


#search

In [6]:
import numpy as np
var  = np.array([1,2,3,4,2,5,2,5,6,7])
var1  = np.array([4,2,3,4,2,5,2,5,6,7])
x = np.where(var==2)
y = np.where((var%2)==0)

print(x)
print()
print(y)

(array([1, 4, 6], dtype=int64),)

(array([1, 3, 4, 6, 8], dtype=int64),)


In [8]:
var1 = np.array([1,2,3,4,6,7,8])
#index           0,1,2,3,4,5,6

x1 = np.searchsorted(var1,5)
print(x)

(array([1, 4, 6], dtype=int64),)


In [12]:
var2 = np.array([1,2,3,4,9,10])
#index           0,1,2,3,4,5

x2 = np.searchsorted(var2,[5,6,7],side ="right")
print(x2)

[4 4 4]


#sort

In [15]:
var_1 = np.array([4,2,3,1,12,5,22,52,6,7])

print(np.sort(var_1))


[ 1  2  3  4  5  6  7 12 22 52]


In [19]:
var_2 = np.array([[4,2,3],[1,2,5],[22,52,6]])

print(np.sort(var_2))

[[ 2  3  4]
 [ 1  2  5]
 [ 6 22 52]]


In [23]:
var_3 = np.array(["a","s","d","f"])
print(np.sort(var_3))


['a' 'd' 'f' 's']


#filter

In [28]:
var_4 = np.array(["a","s","d","f"])
f = [True,False,False,True]
new_a = var_4[f]
print(new_a)
print(type(new_a))

['a' 'f']
<class 'numpy.ndarray'>


#shuffle

In [30]:
var =np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[5 4 2 3 1]


In [38]:
var1 =np.array([1,2,3,4,2,5,2,6,2,7])
x = np.unique(var1,return_index = True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9], dtype=int64))


In [42]:
var2 = np.array([1,2,3,4,5,6])
y = np.resize(var2,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


In [44]:
var3 = np.array([1,2,3,4,5,6])
y = np.resize(var2,(3,2))
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [52]:
var4 = np.array([1,2,3,4,5,6])
v = np.resize(var,(3,2))
print(v)
print()
print(v.flatten(order="f"))
print("ravel= ",np.ravel(v))


[[5 4]
 [2 3]
 [1 5]]

[5 2 1 4 3 5]
ravel=  [5 4 2 3 1 5]


#insert

In [56]:
var6 = np.array([1,2,3,4])
print(var6)
v = np.insert(var6,(2,4),40)
print(v)

[1 2 3 4]
[ 1  2 40  3  4 40]


In [58]:
var7 = np.array([[1,2,3],[1,2,3]])
v1 = np.insert(var1,2,[22,23,24],axis=0)
print(v1)


[ 1  2 22 23 24  3  4  2  5  2  6  2  7]


In [61]:
var9 = np.array([1,2,3,4])
print(var9)

v = np.insert(var,(2,4),6.5)
x = np.append(var,6.5)
print(v)
print()
print(x)

[1 2 3 4]
[5 4 6 2 3 6 1]

[5.  4.  2.  3.  1.  6.5]


In [67]:
var0 = np.array([[1,2,3],[1,2,3]])
v2 = np.append(var1,[45,44,23],axis =0 )

print(v2)

[ 1  2  3  4  2  5  2  6  2  7 45 44 23]


In [69]:
var5 = np.array([1,2,3,4])
print(var5)
d = np.delete(var5,2)
print(d)

[1 2 3 4]
[1 2 4]


#matrix

In [79]:
import numpy as np

var = np.matrix([[1,2,3],[1,2,3]])
print(var)
print(type(var))


var1 = np.array([[1,2,3],[1,2,3]])
print(var1)
print(type(var1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>
[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [81]:
import numpy as np
var = np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[1,2]])
print(var.dot(var2))

[[3 6]
 [3 6]]


In [83]:
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.transpose(var))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [87]:
var1 = np.matrix([[1,2,3],[4,5,6]])
print(var1)
print()
print(np.swapaxes(var1,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [91]:
var2 = np.matrix([[2,2],[3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))

[[2 2]
 [3 4]]

[[2 3]
 [2 4]]


In [95]:
var3 = np.matrix([[1,2],[3,4]])
print(var3)
print()
print(np.linalg.matrix_power(var3,2))
print()
print(np.linalg.matrix_power(var3,0))
print()
      


[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]



In [99]:
var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()
print(np.linalg.det(var4))

[[1 2]
 [3 4]]

-2.0000000000000004
