In [5]:
import numpy as np


marks = np.array([[78,85,90],[92,88,76],[65,70,72],[80,95,89],[90,92,94]])

print("marks of students:\n", marks)

student_avg = np.mean(marks, axis=1)
print("\n Average marks of each student:", student_avg)

subject_avg = np.mean(marks, axis=0)
print("Average marks of each subject:", subject_avg)

highest_marks = np.max(marks, axis=0)
print("Highest marks in each subject:", highest_marks)

total_marks = np.sum(marks, axis=1)
topper_index = np.argmax(total_marks)


print("topper is student", topper_index+1, "with total marks:", total_marks[topper_index])





marks of students:
 [[78 85 90]
 [92 88 76]
 [65 70 72]
 [80 95 89]
 [90 92 94]]

 Average marks of each student: [84.33333333 85.33333333 69.         88.         92.        ]
Average marks of each subject: [81.  86.  84.2]
Highest marks in each subject: [92 95 94]
topper is student 5 with total marks: 276
